return {
    data = {
        animations = {
            {
                animation_id = "show",
                animation_keys = {
                    {
                        easing = "outsine",
                        end_value = -61,
                        key_type = "tween",
                        node_id = "label_image",
                        property_id = "position_y",
                        start_value = -16,
                    },
                    {
                        easing = "outcirc",
                        end_value = -26,
                        key_type = "tween",
                        node_id = "content_text",
                        property_id = "position_y",
                        start_value = 19,
                    },
                    {
                        easing = "outcirc",
                        end_value = -26,
                        key_type = "tween",
                        node_id = "content_text",
                        property_id = "position_y",
                        start_value = -26,
                    },
                    {
                        easing = "outcirc",
                        end_value = -21,
                        key_type = "tween",
                        node_id = "content_text",
                        property_id = "position_y",
                        start_value = -26,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "content",
                        property_id = "color_a",
                        start_value = 0.7,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "content_text",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "label_image",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "label_test",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.3,
                        easing = "outcirc",
                        end_value = -16,
                        key_type = "tween",
                        node_id = "label_image",
                        property_id = "position_y",
                        start_value = -61,
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 0.85,
                        key_type = "tween",
                        node_id = "content",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "content_text",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "label_image",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.3,
                        easing = "outsine",
                        end_value = 1,
                        key_type = "tween",
                        node_id = "label_test",
                        property_id = "color_a",
                    },
                    {
                        duration = 0.3,
                        easing = "outcirc",
                        end_value = 19,
                        key_type = "tween",
                        node_id = "content_text",
                        property_id = "position_y",
                        start_value = -21,
                    },
                },
                duration = 0.3,
                initial_state = "hide",
            },
            {
                animation_id = "hide",
                animation_keys = {
                    {
                        duration = 0.25,
                        easing = "incirc",
                        end_value = -61,
                        key_type = "tween",
                        node_id = "label_image",
                        property_id = "position_y",
                        start_value = -16,
                    },
                    {
                        duration = 0.25,
                        easing = "incirc",
                        end_value = -26,
                        key_type = "tween",
                        node_id = "content_text",
                        property_id = "position_y",
                        start_value = 19,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "content",
                        property_id = "color_a",
                        start_value = 0.7,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "content_text",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "label_image",
                        property_id = "color_a",
                        start_value = 1,
                    },
                    {
                        duration = 0.25,
                        easing = "outsine",
                        key_type = "tween",
                        node_id = "label_test",
                        property_id = "color_a",
                        start_value = 1,
                    },
                },
                duration = 0.25,
            },
        },
        metadata = {
            fps = 60,
            gizmo_steps = {
            },
            gui_path = "gui/widgets/buttons/image_button_overlay/image_button_overlay.gui",
            layers = {
            },
            settings = {
                font_size = 40,
            },
            template_animation_paths = {
            },
        },
        nodes = {
        },
    },
    format = "json",
    type = "animation_editor",
    version = 1,
}