function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	if action_id == hash("mouse_button_1") then --build mode
		if gui.pick_node(gui.get_node("build_button"), action.x, action.y) then
			msg.post("/towers#build", "activateBuildMode")
		end
	end
end