local camera = require("orthographic.camera")

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if (action.x and action.y) then
		local screen = vmath.vector3(action.x, action.y, 0)
		local world = camera.screen_to_world(nil, screen)
		action.x = world.x
		action.y = world.y
	end
	msg.post("#cursor", "input", { action_id = action_id, action = action })
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
